---
- name: Instalación de Zabbix Server 6.0 usando Roles
  hosts: zabbix_servers
  become: yes

  roles:
    - common
    - apache
    - php
    - mariadb
    - firewalld
    - zabbix_server
    - zabbix_agent
    - zabbix_frontend
